const char* TITULO = "                                                                \n"
"               AAA   BBBBBB   UU   UU   SSSSS    CCCCC    AAA   \n"
"              AAAAA  BB   BB  UU   UU  SS       CC       AAAAA  \n"
"             AA   AA BBBBBB   UU   UU   SSSSS   CC       AA   AA \n"
"            AAAAAAAA BB   BB  UU   UU       SS  CC      AAAAAAAA \n"
"           AA     AA BBBBBB    UUUUU    SSSSS    CCCCC  AA     AA\n"
"                                                                \n"
"                              DDDDD      OOO                      \n"
"                              DD  DD    O   O                     \n"
"                              DD   DD  O     O                    \n"
"                              DD  DD    O   O                     \n"
"                              DDDDD      OOO                      \n"
"                                                                \n"
"     AAA   MM    MM UU   UU LL       EEEEEE TTTTTTT   OOO      SSSSS    AAA    GGGGGG  RRRRRR     AAA   DDDDD      OOO      \n"
"    AAAAA  MMM  MMM UU   UU LL       EE       TTT    O   O    SS       AAAAA  GG       RR   RR   AAAAA  DD  DD    O   O     \n"
"   AA   AA MM MM MM UU   UU LL       EEEE     TTT   O     O    SSSSS   AA   AA GG   GGG RRRRRR   AA   AA DD   DD  O     O    \n"
"  AAAAAAAA MM    MM UU   UU LL       EE       TTT    O   O        SS AAAAAAAA GG    GG RR  RR  AAAAAAAA DD  DD    O   O     \n"
" AA     AA MM    MM  UUUUU  LLLLLLLL EEEEEE   TTT     OOO     SSSSS  AA     AA  GGGGGG  RR   RR AA     AA DDDDD      OOO      \n"
"";

const char* FLORESTA = "                                                                \n"
"                               ,d$$b.                            \n"
"                             ,d$'$'$b.                           \n"
"                          ,d$P   `Y$b.                          \n"
"                         ,d$P     `Y$b.                         \n"
"                        ,d$P       `Y$b.                        \n"
"                       ,d$P         `Y$b.                       \n"
"                      ,d$P           `Y$b.                      \n"
"                     ,d$P             `Y$b.                     \n"
"                    ,d$P               `Y$b.                    \n"
"                   ,d$P                 `Y$b.                   \n"
"                  ,d$P                   `Y$b.                  \n"
"                 ,d$P                     `Y$b.                 \n"
"                ,d$P                       `Y$b.                \n"
"               ,d$P                         `Y$b.               \n"
"              ,d$P                           `Y$b.              \n"
"             ,d$P                             `Y$b.             \n"
"            ,d$P                               `Y$b.            \n"
"           ,d$P                                 `Y$b.           \n"
"          ,d$P                                   `Y$b.          \n"
"         ,d$P                                     `Y$b.         \n"
"        ,d$P                                       `Y$b.        \n"
"       ,d$P                                         `Y$b.       \n"
"      ,d$P                                           `Y$b.      \n"
"     ,d$P                                             `Y$b.     \n"
"    ,d$P                                               `Y$b.    \n"
"   ,d$P                                                 `Y$b.   \n"
"  ,d$P                                                   `Y$b.  \n"
" ,d$P                                                     `Y$b. \n"
",d$P                                                       `Y$b.\n"
"";

const char* GOBLIN_FADA = "                                                                \n"
"                 ,      ,                                       \n"
"                /(      )`                                      \n"
"                \\ \\____( (   /                                  \n"
"                 \\ \\___ ` ) /                                   \n"
"                  )   \\ `)/                                     \n"
"                 /    /` )                                      \n"
"                /    (  /                                       \n"
"               /      \\/                                        \n"
"              /        |                                        \n"
"             /         |                                        \n"
"            /          |                                        \n"
"           /           |                                        \n"
"          /            |                                        \n"
"         /             |                                        \n"
"        /              |                                        \n"
"       /               |                                        \n"
"      /                |                                        \n"
"     /                 |                                        \n"
"    /                  |                                        \n"
"   /                   |                                        \n"
"  /                    |                                        \n"
" /                     |                                        \n"
"/______________________|                                        \n"
"";

const char* ELFA_CACHOEIRA = "                                                                \n"
"                                                                \n"
"                      ,                                         \n"
"                     / \\                                        \n"
"                    /   \\                                       \n"
"                   /     \\                                      \n"
"                  /       \\                                     \n"
"                 /         \\                                    \n"
"                /           \\                                   \n"
"               /             \\                                  \n"
"              /               \\                                 \n"
"             /                 \\                                \n"
"            /                   \\                               \n"
"           /                     \\                              \n"
"          /                       \\                             \n"
"         /                         \\                            \n"
"        /                           \\                           \n"
"       /                             \\                          \n"
"      /                               \\                         \n"
"     /                                 \\                        \n"
"    /                                   \\                       \n"
"   /                                     \\                      \n"
"  /                                       \\                     \n"
" /                                         \\                    \n"
"/___________________________________________\\                   \n"
"";

const char* PANTANO = "                                                                \n"
"                          '                        '      '       \n"
"                     '                 '     '                    \n"
"    '                             '                               \n"
"               '        '              '   '          '     '    \n"
"                               '                                  \n"
"         '            '              '   '       '                \n"
"                             '                                '   \n"
"    '       '    '        '   '      '       '         '          \n"
"                                                                \n"
" '     '                 '      '                '  '            \n"
"           '      '             '   '        '            '      \n"
"                                                                \n"
"      '           '      '             '   '        '     '      \n"
"                              '     '     '                       \n"
" '       '     '     '           '           '      '     '      \n"
"                                                                \n"
"           '      '     '     '     '        '      '            \n"
"                                                                \n"
" '     '                 '      '                '  '      '     \n"
"           '      '             '   '        '            '      \n"
"                                                                \n"
"      '           '      '             '   '        '            \n"
"                '     '     '     '     '      '                  \n"
" '       '     '     '           '           '      '     '      \n"
"";

const char* BRUXA = "                                                                \n"
"                     .---.                                        \n"
"                    /     \\                                       \n"
"                    \\.@-@./                                       \n"
"                    /`\\_/`\\                                       \n"
"                   //  _  \\\\                                      \n"
"                  | \\     )|_                                     \n"
"                 /`SIAN`\\  `\\                                     \n"
"                /       /\\ ___\\                                   \n"
"                `------' ` \\                                     \n"
"                 `뭣'                                            \n"
"";

const char* CAVERNA = "                                                                \n"
"                      /\\                                        \n"
"                     /  \\                                       \n"
"                    /    \\                                      \n"
"                   /      \\                                     \n"
"                  /        \\                                    \n"
"                 /          \\                                   \n"
"                /            \\                                  \n"
"               /              \\                                 \n"
"              /                \\                                \n"
"             /                  \\                               \n"
"            /                    \\                              \n"
"           /                      \\                             \n"
"          /                        \\                            \n"
"         /                          \\                           \n"
"        /                            \\                          \n"
"       /                              \\                         \n"
"      /                                \\                        \n"
"     /                                  \\                       \n"
"    /                                    \\                      \n"
"   /                                      \\                     \n"
"  /                                        \\                    \n"
" /                                          \\                   \n"
"/____________________________________________\\                  \n"
"";

const char* DRAGAO_FILHOTE = "                                                                \n"
"                     .                                          \n"
"                    / \\                                         \n"
"                   /   \\                                        \n"
"                  /     \\                                       \n"
"                 /       \\                                      \n"
"                /         \\                                     \n"
"               /           \\                                    \n"
"              /             \\                                   \n"
"             /_______________\\                                  \n"
"                 |       |                                      \n"
"                 |_______|                                      \n"
"                 | -   - |                                      \n"
"                 |   o   |                                      \n"
"                 |_______|                                      \n"
"";

const char* FERREIRO = "                                                                \n"
"          ____                                                  \n"
"         /    \\                                                 \n"
"        /      \\                                                \n"
"       /        \\                                               \n"
"      /__________\\                                              \n"
"          |  |                                                  \n"
"        O |__| O                                                \n"
"      / \\      / \\                                              \n"
"     /   \\____/   \\                                             \n"
"    /              \\                                            \n"
"   /________________\\                                           \n"
"";

const char* CASTELO = "                                                                \n"
"                     |>>>                                       \n"
"                     |                                          \n"
"                 _  _|_  _                                      \n"
"                |;|_|;|_|;|                                     \n"
"                \\\\.    .  /                                   \n"
"                 \\\\:  .  /                                    \n"
"                  ||:   |                                       \n"
"                  ||:.  |                                       \n"
"                  ||:  .|                                       \n"
"                  ||:   |       \\,                              \n"
"                  ||: , |            /`\\                          \n"
"                  ||:   |         .'  /_                         \n"
"                  ||: . |      /` /   /`\\                        \n"
"                  ||:   |   /`  /    /   \\                       \n"
"                  ||: . |  /  .`    / `) /                       \n"
"                  ||:   |/    -----`--(.'                        \n"
"                  ||:    /                                    \n"
"                  ||:  /`                                     \n"
"                  ||:/                                        \n"
"                  |;`                                         \n"
"";

const char* CONFRONTO_FINAL = "                                                                \n"
"                      / \\                                         \n"
"                     /   \\                                        \n"
"                    /     \\                                       \n"
"                   /       \\                                      \n"
"                  /         \\                                     \n"
"                 /           \\                                    \n"
"                /             \\                                   \n"
"               /_______________\\                                  \n"
"                   |       |                                      \n"
"                   |_______|                                      \n"
"                   | O   O |                                      \n"
"                   |   ^   |                                      \n"
"                   |_______|                                      \n"
"";